/*
	UIZE JAVASCRIPT FRAMEWORK 2010-10-21

	http://www.uize.com/reference/Uize.Data.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Data',builder:function(){var _a=function(){},_b='string',_c=true,_d=false,_e=null;var _f={};_a.getColumn=function(_g,_h,_i){var _j=[];if(_g){var _k=_i?{}:_e;for(var _l= -1,_m=_g.length;++_l<_m;){var _n=_g[_l][_h];if(!_i||(!_k[_n]&&(_k[_n]=1)))_j.push(_n);}}return _j;};_a.findRecords=function(_o,_p){var _q=[];if(_o){for(var _r= -1,_s=_o.length,_t;++_r<_s;)Uize.recordMatches(_t=_o[_r],_p)&&_q.push(_t);}return _q;};_a.getKeys=function(_u){var _j=[];if(typeof _u!=_b)for(var _v in _u)_j.push(_v);return _j;};_a.getTotalKeys=function(_u){var _j=0;if(typeof _u!=_b)for(var _v in _u)_j++;return _j;};_a.getLookup=function(_w,_x){var _y={};if(arguments.length==1)_x=_c;for(var _z= -1,_A=_w.length;++_z<_A;)_y[_w[_z]]=_x;return _y;};_a.getReverseLookup=function(_u){var _y={};if(typeof _u!=_b)for(var _v in _u)_y[_u[_v]+'']=_v;return _y;};_a.getValues=function(_u){if(Uize.isArray(_u))return _u;var _j=[];if(typeof _u!=_b)for(var _v in _u)_j.push(_u[_v]);return _j;};_a.isEmpty=function(_u){
if(_u&&typeof _u=='object'&&_u.constructor!=_f.constructor)_u=_u.valueOf();if(!_u)return _c;if(Uize.isArray(_u))return!_u.length;if(typeof _u=='object'){for(var _v in _u)return _d;return _c;}return!_u;};_a.emptyOut=function(_B){if(typeof _B=='object'&&_B){if(Uize.isArray(_B)){_B.length=0;}else{for(var _C in _B)delete _B[_C];}}return _B;};_a.filter=function(_u,_D){var _E=this,_j={};if(_u&&_D){for(var _F= -1,_G=_D.length;++_F<_G;){var _H=_D[_F];if(_H in _u)_j[_H]=_u[_H];}}return _j;};_a.identical=function(_I,_J,_K){if(!_K)_K=_f;var _L=_K.equality,_M=_L=='loose',_N= !_M&&_L!='type',_O=_K.allowConjoined!==_d;function _P(_I,_J){var _Q,_R=typeof _I,_S=_R==typeof _J,_T=_R=='object';if(_S&&_T&&_I&&_J){if(_I==_J){_Q=_O;}else if(_Q=_I.constructor==_J.constructor){if(_I instanceof Date){_Q= +_I== +_J;}else if(_Q=(typeof _I.length!='number'||_I.length===_J.length)&&_a.getTotalKeys(_I)==_a.getTotalKeys(_J)){for(var _H in _I){if(!(_H in _J)|| !_P(_I[_H],_J[_H])){_Q=_d;break;}}}}}else{_Q=(_M?_I==_J:(_S&&
(_N?_I===_J:(!_T|| !_I== !_J))))||(_S&&_R=='number'&&isNaN(_I)&&isNaN(_J));}return _Q;}return _P(_I,_J);};_a.conjoined=function(_I,_J){function _U(_u){var _V=[];function _W(_u){if(typeof _u=='object'){if(!Uize.isIn(_V,_u)){_V.push(_u);for(var _H in _u)_W(_u[_H]);}}}_W(_u);return _V;}var _X=_d,_Y=_U(_I),_Z=_Y.length,_0=_U(_J);for(var _1= -1;++_1<_Z&& !_X;)_X=Uize.isIn(_0,_Y[_1]);return _X;};_a.clones=function(_I,_J){return(_a.identical(_I,_J,{allowConjoined:_d})&& !_a.conjoined(_I,_J));};_a.intersection=function(_I,_J){var _j={};if(_I&&_J){for(var _H in _I){var _2=_I[_H];if(_J[_H]===_2)_j[_H]=_2;}}return _j;};_a.map=function(_3,_B,_4){if(typeof _B=='number'){_B=new Array(_B);if(typeof _4!='object')_4=_B;}var _5=Uize.isArray(_B);if(typeof _4!='object')_4=_4===_d?_B:_5?[]:{};if(typeof _3==_b)_3=new Function('value','key','return '+_3);function _6(_v){var _7=_3.call(_B,_B[_v],_v);if(_4)_4[_v]=_7;}if(_5){for(var _8= -1,_9=_B.length;++_8<_9;)_6(_8);}else{for(var _v in _B)_6(_v);}return _4;};_a.min=function(_u){
return Math.min.apply(0,_a.getValues(_u));};_a.max=function(_u){return Math.max.apply(0,_a.getValues(_u));};return _a;}});