/*
	UIZE JAVASCRIPT FRAMEWORK 2010-09-06

	http://www.uize.com/reference/Uize.Doc.Simple.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Doc.Simple',required:['Uize.Data.Simple','Uize.String','Uize.Templates.List','Uize.Array.Sort'],builder:function(){var _a,_b='string',_c=function(){},_d={},_e=Uize.String.limitLength;var _f='[-\\*~:\\.]',_g=new RegExp(_f),_h=new RegExp('^\\s*'+_f+'\\s*$'),_i='([@#\\+a-zA-Z]|\\d+)',_j=new RegExp(_i),_k=new RegExp('^([<\\(\\{\\[]*\\s*'+_i+'?\\s*[>\\)\\}\\]]*\\s*'+_f+'*\\s+)'),_l={47:1,92:1};var _m=_c.build=function(_n){function _o(_p,_q){var _r=_n[_p];return typeof _r==_b?_r:_q;}var _s=_n.data,_t=_n.urlDictionary||_d,_u=_n.pathToRoot||'',_v=_o('indentChars','\t'),_w=_o('headingNumberingSeparator','. '),_x=_o('headingNumberingDelimiter','.'),_y=[0],_z=[0],_A=[],_B={items:[]};if(typeof _s==_b)_s=Uize.Data.Simple.parse({simple:_s,parseName:false});function _C(_s){var _D=_s.children;if(_D.length){var _E={};for(var _F= -1;++_F<_D.length;){var _G=_D[_F],_H=_G.children;if(_H.length){var _I=_G.value,_J=_E[_I];if(_J){_J.children=_J.children.concat(_H);_D.splice(_F,1);_F--;}else{_E[_I]=_G;}}}
for(var _F= -1,_K=_D.length;++_F<_K;)_C(_D[_F]);}}_n.canonicalizePeerSections!==false&&_C(_s);var _L=_n.sectionsToSort;if(_L){var _M=_L.length,_N={};for(var _O= -1;++_O<_M;)_N[_L[_O]]=1;function _P(_s){var _D=_s.children,_K=_D.length;if(_K){_N[_s.value]&&Uize.Array.Sort.sortBy(_D,'value.value');for(var _F= -1;++_F<_K;)_P(_D[_F]);}}_P(_s);}var _Q={},_R=[0];function _S(_s,_T,_U){if(typeof _T!='number')_T=0;if(typeof _U!=_b)_U='';var _D=_s.children,_V=_s.value,_W={};if(_D.length){_R[_T]++;var _X=_T?(_U+(_U?'_':'')+_R[_T]):'';_Q[_V]=_X;_R[_T+1]=0;for(var _F= -1,_K=_D.length;++_F<_K;)_S(_D[_F],_T+1,_X);}}_S(_s);function _Y(_Z,_0){function _1(_2,_3,_4,_5,_6){if(_0)return _3;var _7=_5=='url';if(_5&& !_7){if(_5=='text')_6=_3;var _8=_Q[_6];_8?(_6='#'+_8):((_6=_t[_6]||'')&&(_7=true));}if(_l[_6.charCodeAt(0)])_6=_u+_6.slice(1);return(_2+(_6?('<a href="'+_6+'"'+(_7&&/^[a-zA-Z]+:/.test(_6)?' target="_blank" class="externalSiteLink"':'')+'>'+_3+'</a>'):_3)+_4);}return(_Z.replace(/^#(\S*)/,
function(_9,_ba){return _1('<a name="'+_ba+'">','','</a>')}).replace(/\B\*.+?\*\B/g,function(_9){return _1('<b>',_9.slice(1,-1),'</b>','text')}).replace(/\b__.+?__\b/g,function(_9){return _1('<b><i>',_9.slice(2,-2),'</i></b>','text')}).replace(/\b_.+?_\b/g,function(_9){return _1('<i>',_9.slice(1,-1),'</i>','text')}).replace(/\B==.+?==\B/g,function(_9){return _1('<code><b>',_9.slice(2,-2),'</b></code>','text')}).replace(/\B=.+?=\B/g,function(_9){return _1('<code>',_9.slice(1,-1),'</code>','text')}).replace(/\B`.+?`\B/g,function(_9){return _1('',_9.slice(1,-1),'','text')}).replace(/\[\[(#.+?|[a-zA-Z]+:.+?|.+?\.(?:htm|html|jpg|gif|png)(?:[\?#][^\]]*)?)\]\[(.+?)\]\]/g,function(_9,_bb,_bc){return _1('',_bc,'','url',_bb)}).replace(/\[\[(.+?)\]\[(.+?)\]\]/g,function(_9,_bd,_bc){return _1('',_bc,'','section',_bd)}).replace(/\[\[(#.+?|[a-zA-Z]+?:.+?)\]\]/g,function(_9,_bb){return _1('',_bb,'','url',_bb)}).replace(/\[\[(.+?)\]\]/g,function(_9,_bd){return _1('',_bd,'','text')}));}function _be(_s,_T,_bf,_bg,_bh,_bi,_bj){
function _bk(_bl){_A.push(_bg+_bl)}function _bm(_bn){var _bo=_T+ !!_bn;if(_z[_bo]){_bk((_bn?_v:'')+'</table>');_z[_bo]=0;}}var _D=_s.children,_V=_s.value,_bp;if(!_D.length){if(/\r|\n|\r\n/.test(_V)){_bm();_bk('');_bk('<pre class="sample-code">'+_bq(_V)+'</pre>');_bk('');}else if(/^={3,}$/.test(_V)){_bm();_bk('<hr class="thick"/>');}else if(/^-{3,}$/.test(_V)){_bm();_bk('<hr class="thin"/>');}else if((_bp=_V.match(_k))&&/[^\w\s\d]/.test(_bp[1])){var _br=_bp[1],_bs=_br.match(_j);_z[_T]||_bk('<table class="list">');if(_bs){var _bt=_bs[1],_bu='';if(/[#\+]|\d+/.test(_bt)){_bu=_z[_T]+1+'';}else if(/[@a-z]/i.test(_bt)){_bu='abcdefghijklmnopqrstuvwxyz'.charAt(_z[_T]);if(/[A-Z]/.test(_bt))_bu=_bu.toUpperCase();}_br=_br.replace(_j,_bu)}else{_br=_h.test(_br)?_br.replace(_g,'<span class="bullet"></span>'):_bq(_br);}_bk('<tr valign="top">'+'<td><span style="white-space:nowrap;">'+_br+'</span></td>'+'<td>'+_Y(_V.replace(_k,''))+'</td>'+'</tr>');_z[_T]++;}else{_bm();var _bv=_Y(_V);if(/[A-Z]/.test(_bv)&& !/[a-z]/.test(_bv))
_bv='<span class="allCaps">'+_bv+'</span>';_bk('<p>'+_bv+'</p>');_bk('');}}else{_bm();_y[_T]++;var _bw=_T>0,_bx=_bw?(_bh+(_bh?'_':'')+_y[_T]):'',_by=_bx.replace(/_/g,_x)+(_bx?_w:'')+_V,_bz=(_bi?(_bi+' -> '):'')+_by,_bA=_bw?((_bj?(_bj+_x):'')+'<a href="#'+_bx+'" title="'+_bz+'">'+_y[_T]+'</a>'):'',_bB={title:_by||'Contents',description:_D[0].children.length?'':_e(_Y(_D[0].value,true),400),link:_bx?('#'+_bx):'',items:[]};_bf.items.push(_bB);if(_V){var _bC='h'+Math.min(_T,5),_bD=_bA+_w;_bk('<a name="'+_bx+'"></a>');_bk('<'+_bC+' class="heading'+_T+'" title="'+_bz+'">'+(_bA?'<span class="headingNumber">'+_bD+'</span>':'')+_V+'</'+_bC+'>');}_bk('<div class="contents'+_T+'">');_y[_T+1]=_z[_T+1]=0;for(var _F= -1,_K=_D.length;++_F<_K;)_be(_D[_F],_T+1,_bB,_bg+_v,_bx,_bz,_bA);_bm(true);/\S/.test(_A[_A.length-1])||_A.pop();_bk('</div>');_bk('');}}_be(_s,0,_B,'','','','');var _bE=_B.items,_bF=(_n.contentsList!==false&&(_bE.length&&(_bE.length>1||_bE[0].items.length))?(
'<div id="page_contents" class="contents-tree-shell">\n'+Uize.Templates.List.process({items:_bE})+'\n'+'</div>\n'+'\n'):'')+_A.join('\n');return(_n.result=='full'?{html:_bF,contentsTreeItems:_bE}:_bF);};_c.toDocument=function(_bG){return _m({data:_bG})};var _bq=_c.toSampleCode=function(_bH){return _bH.replace(/\t/g,'  ').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');};return _c;}});