/*
	UIZE JAVASCRIPT FRAMEWORK 2010-08-30

	http://www.uize.com/reference/Uize.Widget.Collection.Dynamic.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Collection.Dynamic',required:['Uize.Node','Uize.Widget.Drag','Uize.Tooltip'],builder:function(d_a){var d_b=true,d_c=false,d_d=null,d_e=Uize.Node,d_f=Uize.Tooltip;var d_g=d_a.subclass(d_d,function(){var d_h=this;var d_i,d_j,d_k,d_l,d_m,d_n,d_o,d_p,d_q,d_r,d_s,d_t,d_u,d_v,d_w,d_x,d_y,d_z=d_h.addChild('drag',Uize.Widget.Drag,{nodeMap:{'':d_d}});function d_A(d_B){var d_C=d_B?d_h.d_D:1,d_E=d_h.getNode('tooltipDragging');for(var d_F=d_l;--d_F> -1;)d_k[d_F].setNodeOpacity('',d_C);d_B&&d_e.setInnerHtml(d_E,d_h.localize('draggingToReorder'+(d_l>1?'Plural':'Singular'),{totalItems:d_l}));d_f.showTooltip(d_E,d_B,d_b);}d_z.wire({'Drag Start':function(){d_j=d_h.d_G=='reverse'?1:0;d_i.set({over:d_c});var d_H=d_i.get('selected');if(!d_H){d_h.selectAll(d_c);d_h.d_I&&d_i.set({selected:d_b});}if(!d_h.d_J){if(d_H){for(var d_K= -1,d_L=d_h.getSelected(),d_M=d_L.length;++d_K<d_M;)d_L[d_K].get('locked')&&d_L[d_K].set({selected:d_c});d_h.get('totalSelected')||d_z.set({dragCancelled:d_b});}
else if(d_i.get('locked'))d_z.set({dragCancelled:d_b});}d_k=d_H?d_h.getSelected():[d_i];d_l=d_k.length;d_m=[];d_h.forAll(function(d_N){d_m.push(d_e.getCoords(d_N.getNode()));});var d_O=d_m.length,d_P=d_O-1,d_Q=d_m[d_j?d_P:0],d_R=d_m[d_j?d_P-1:1];d_u=d_P&&d_R.top>d_Q.bottom?1:0;d_x=d_u?'top':'left';d_y=d_u?'height':'width';d_p=d_q=d_r=d_s=d_t=d_d;d_v=d_h.getNode('insertionMarker');d_w=d_e.getDimensions(d_v);for(var d_S= -1,d_T=d_P?d_R[d_x]-(d_Q[d_x]+d_Q[d_y]-1):0,d_U=d_T/2;++d_S<d_O;){var d_V=d_m[d_S];d_V[d_x]-=d_U;d_V[d_y]+=d_T;}d_A(d_b);},'Drag Update':function(d_W){var d_X=document.documentElement,d_Y=d_z.eventPos;d_f.positionTooltip(d_h.getNode('tooltipDragging'),{pageX:d_Y[0],pageY:d_Y[1]});function d_Z(d_0){return(d_0&&d_e.doRectanglesOverlap(d_0.left,d_0.top,d_0.width,d_0.height,d_Y[0],d_Y[1],1,1));}if(!d_Z(d_o)){d_n=d_o=d_d;d_h.forAll(function(d_N,d_S){var d_V=d_m[d_S];if(d_Z(d_V)){d_n=d_N;d_o=d_V;}return!d_n;});}if(!d_Z(d_r)){d_p=d_r=d_d;if(d_n&& !d_g.isIn(d_k,d_n)){var d_1=d_o[d_y],d_2=d_1/2,
d_3=d_o[d_x],d_4=d_3+d_2;d_p=d_n;d_q=d_Y[d_u]<d_4?0:1;d_r=d_g.clone(d_o);d_r[d_x]=d_q?d_4:d_3;d_r[d_y]=d_2;}}if(d_p!=d_s||d_q!=d_t){d_h.displayNode(d_v,!!d_p);if(d_p){var d_5=d_g.clone(d_r);d_5[d_x]+=(d_q?d_r[d_y]:0)-d_w[d_y]/2;delete d_5[d_y];d_e.setCoords(d_v,d_5);}d_s=d_p;d_t=d_q;}d_z.set({cursor:d_p||d_n?'move':'not-allowed'});},'Drag Done':function(d_W){if(d_z.get('dragStarted')){d_A(d_c);d_h.displayNode('insertionMarker',d_c);function d_6(){if(d_p&& !d_z.get('dragCancelled')){var d_7=d_h.itemWidgets;if(d_q^d_j){var d_8=d_7.length,d_9=d_g.indexIn(d_7,d_p)+1;d_p=d_d;while(d_9<d_8){var d_N=d_7[d_9];if(!d_g.isIn(d_k,d_N)){d_p=d_N;break;}else{d_9++;}}}for(var d_F= -1;++d_F<d_l;)d_h.move(d_k[d_F],d_p);d_h.fire('Items Reordered');d_h.d_ba();}}d_h.d_bb?d_h.confirm({state:'warning',title:d_h.localize('confirmDragToReorderTitle'),message:d_h.localize('confirmDragToReorderPrompt'),yesHandler:function(){d_h.d_bb=d_c;d_h.fire('Drag Confirmed');d_6();},noHandler:function(){d_z.set({dragCancelled:true});}}):d_6();}}
});d_h.wire('Item Mouse Down',function(d_W){if(d_h.d_bc){d_i=d_W.source;d_z.initiate(d_W.domEvent);}d_W.bubble=d_c;});}),d_bd=d_g.prototype;d_bd.d_be=function(d_bf){var d_h=this,d_bg=d_bf.properties,d_bh=d_h.makeItemWidgetName(d_bg),d_bi=d_h.getNode('itemTemplate');if(d_bi)d_bf.html=d_bi.innerHTML.replace(/ITEMWIDGETNAME/g,d_bh);d_bf.built=d_c;d_bf.container=d_h.getNode('items');d_bf.insertionMode=d_h.d_G=='reverse'?'inner top':'inner bottom';d_h.get('items').push(d_bg);return d_h.addItemWidget(d_bh,d_bf);};d_bd.d_ba=function(){this.fire('Items Changed')};d_bd.d_bj=function(d_N){d_N.removeUi();d_N.kill();this.removeChild(d_N);};d_bd.d_bk=function(){var d_h=this;d_h.forAll(function(d_N){d_h.d_bj(d_N)});};var d_bl={selected:d_b};d_bd.add=function(d_bm){var d_h=this,d_bn=[];if(d_h.isWired){if(!d_g.isArray(d_bm))d_bm=[d_bm];var d_bo=d_bm.length;if(d_bo){d_h.d_bp&&d_h.selectAll(d_c);var d_bq=d_h.d_bp?d_bl:d_d;for(var d_br= -1;++d_br<d_bo;)d_bn.push(d_h.d_be(d_g.copyInto(d_bm[d_br],d_bq)));}d_h.d_ba();}return d_bn;
};d_bd.getItemWidgetProperties=function(){var d_h=this;return(d_g.copyInto({previewTooltip:function(){return d_h.d_bc?d_h.getNode('tooltipDragToReorder'):d_d}},d_h.get('itemWidgetProperties')));};d_bd.finishRemove=function(d_bs,d_bt){var d_h=this,d_bu=d_h.get('items'),d_7=d_h.itemWidgets,d_8=d_7.length,d_bv=d_bs,d_bw=d_bs.length;if(d_bw==d_8){d_h.d_bk();}else{d_bv=[];d_bw=0;var d_bx=d_d;d_h.forAll(function(d_N,d_S){if(d_g.isIn(d_bs,d_N)){d_bx=d_d;d_bv.push(d_N);d_bw++;d_h.d_bj(d_N,d_S);}else{if(!d_bx&& !d_N.get('locked'))d_bx=d_N;if(d_bw){d_bu[d_S-d_bw]=d_bu[d_S];d_7[d_S-d_bw]=d_N;}}});}if(d_bw){d_bu.length=d_7.length=d_8-d_bw;d_h.fire({name:'Items Removed',byUser:d_bt,totalBeforeRemove:d_8,itemWidgetsRemoved:d_bv,totalRemoved:d_bw,percentRemoved:d_bw/d_8*100});d_h.d_ba();}};d_bd.move=function(d_by,d_bz){var d_h=this,d_bA=d_h.d_G=='reverse',d_bB=d_bz?d_bz.getNode():d_d,d_bu=d_h.get('items'),d_7=d_h.itemWidgets,d_bC=d_h.getNode('items'),d_bD=d_by.getNode(),d_bE=d_bA?(d_bB?d_bB.nextSibling:d_bC.childNodes[0])
:d_bB;d_bE?d_bC.insertBefore(d_bD,d_bE):d_bC.appendChild(d_bD);var d_bF=d_g.indexIn(d_7,d_by),d_bG=d_bu[d_bF];d_7.splice(d_bF,1);d_bu.splice(d_bF,1);var d_bH=d_bz?d_g.indexIn(d_7,d_bz):d_7.length-(d_bA?0:1);d_7.splice(d_bH,0,d_by);d_bu.splice(d_bH,0,d_bG);};d_g.registerProperties({d_bb:{name:'confirmToDrag',value:d_c},d_J:{name:'dragIgnoresLocked',value:d_b},d_bc:{name:'dragToReorder',value:d_c},d_I:{name:'ensureItemDraggedIsSelected',value:d_c},d_G:{name:'itemDisplayOrder',value:'normal'},d_bp:{name:'makeNewlyAddedSelected',value:d_b},d_D:{name:'itemVestigeOpacity',value:.2}});return d_g;}});