/*______________
|       ______  |   B U I L T     O N     U I Z E     F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |   This JavaScript application is developed using the object
|   /    / /    |   oriented UIZE JavaScript framework as its foundation.
|  /    / /  /| |
| /____/ /__/_| |    ONLINE : http://www.uize.com
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.WidgetToGoPage.library Library Module
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2010 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*?
	Introduction
		The =UizeDotCom.WidgetToGoPage.library= module is a library module that bundles together various JavaScript modules common to all pages of the UIZE JavaScript Framework's Web site that use the =UizeDotCom.WidgetToGoPage= page widget class.

		*DEVELOPERS:* `Chris van Rensburg`
*/



Uize.module({name:'UizeDotCom'});


Uize.module({name:'Uize.Node',builder:function(){var _a=function(){},_b,_c='string',_d='function',_e=true,_f=false,_g=null,_h=typeof navigator!='undefined',_i=_h?navigator:{userAgent:'',appName:''},_j=_i.userAgent.toLowerCase(),_k=_i.appName=='Microsoft Internet Explorer',_l=_j.indexOf('applewebkit')> -1,_m=_j.indexOf('gecko')> -1,_n=_j.indexOf('opera')> -1,_o=_m||_n,_p='hidden',_q=Uize.copyInto;var _r=_a._r=function(_s){_t.clientX=_s.clientX;_t.clientY=_s.clientY;_t.pageX=_s.pageX;_t.pageY=_s.pageY;};function _u(_v){var _w=document.getElementById(_v);return(!_k||(_w&&_w.id==_v))?_w:_g;}function _x(){return document[_l?'body':'documentElement'];}function _y(_z){var _A=(_z=_z+'').slice(_z.indexOf('(')+1,_z.indexOf(')'));return Function.apply({},(_A?_A.split(','):[]).concat(_z.slice(_z.indexOf('{')+1,_z.lastIndexOf('}'))));}function _B(_C){if(_C.charCodeAt(0)==111&&_C.charCodeAt(1)==110)_C=_C.slice(2);return(_C.charCodeAt(_C.length-1)==41&&_a.VirtualEvent?_a.VirtualEvent.resolve(_C):_C);}function _D(_E,_F){for(
var _G= -1,_w={},_H=Math.min(_E.length,_F.length);++_G<_H;)_w[_E[_G]]=_F[_G];return _w;}var _I=_a._I={},_J={},_K=0,_L={string:1,number:1,boolean:1},_t={clientX:0,clientY:0,pageX:0,pageY:0};var _M='table-',_N=_M+'row',_O=_M+'cell',_P=_q({SPAN:'inline',THEAD:_M+'header-group',TFOOT:_M+'footer-group',LI:'list-item'},_k&&typeof DOMImplementation=='undefined'?_g:{TABLE:'table',TR:_N,TH:_O,TD:_O,TBODY:_N+'-group',COLGROUP:_M+'column-group',COL:_M+'column',CAPTION:_M+'caption'});_a.display=function(_Q,_R){_R=_R===_b|| !!_R;_S(_Q,function(_T){_T.style.display=_R?(_P[_T.tagName]||'block'):'none';});};var _S=_a.doForAll=function(_Q,_z,_U,_V){if(typeof _Q==_c)_Q=_W(_Q,_U,_V);if(_Q!=_b){if(_X(_Q)){_z(_Q);}else{var _Y=typeof _Q;if((_Y=='object'||_Y==_d)&&typeof _Q.length=='number'){for(var _Z= -1,_0=_Q.length;++_Z<_0;)_S(_Q[_Z],_z,_U,_V);}else if(_Y=='object'){for(var _1 in _Q)_S(_Q[_1],_z,_U,_V);}}}};var _2=_a.doRectanglesOverlap=function(_3,_4,_5,_6,_7,_8,_9,_ba){return(_5-1+ +_3>=_7&&_9-1+ +_7>=_3&&
_6-1+ +_4>=_8&&_ba-1+ +_8>=_4);};var _W=_a.getById=function(_T,_U,_V){if(typeof _T!=_c)return _T;var _w=_V?_V[_T]:_b;if(_w===_b){var _bb=_bc(_U,_T);(_w=_u(_bb))||(((_w=document.getElementsByName(_bb)).length<2)&&(_w=_w[0]||_g));if(_V)_V[_T]=_w;}return _w;};_a.find=function(_bd){if(typeof _bd!='object'|| !_bd||typeof _bd.length=='number'||_X(_bd))return _bd;var _be=document,_bf=[],_bg=_q({},_bd),_bh='root'in _bg?_W(_bg.root):_be;delete _bg.root;if(_bh){var _bi=_bg.tagName;if('id'in _bg&&_L[typeof _bg.id]){var _T=_u(_bg.id);_T&&_bf.push(_T);delete _bg.id;}else if('name'in _bg&&_L[typeof _bg.name]){_bf=_be.getElementsByName(_bg.name);delete _bg.name;}else{var _bj=_L[typeof _bi];_bj&&delete _bg.tagName;_bf=_bh.getElementsByTagName(_bi&&_bj?_bi:'*');_bh=_g;}if(_bh==_be)_bh=_g;if(!_bi||_bi=='*')delete _bg.tagName;}var _bk=_bf.length;for(var _bl in _bg)break;if(!_bk||(_bl==_b&& !_bh))return _bf;var _bm=[],_bn;for(var _bo= -1;++_bo<_bk;){var _T=_bf[_bo];if(_bn=_bh?_bp(_T,_bh):_e){for(var _bq in _bg){var _br=_T[_bq],
_bs=_bg[_bq],_bt=typeof _bs;if(!(_L[_bt]?_br==_bs:(_bs instanceof RegExp?_bs.test(_br||''):(_bt==_d?_bs.call(_T,_br):_e)))){_bn=_f;break;}}}_bn&&_bm.push(_T);}return _bm;};var _bu=_a.getCoords=function(_T){var _bv=0,_bw=0,_bx=0,_by=0,_bz=_e,_bA=_x(),_bB=_bC(window);function _bD(){_bv+=_bA.scrollLeft;_bw+=_bA.scrollTop;}if(_T==window){_bD();_bx=_bB.width;_by=_bB.height;}else if(_X(_T=_W(_T))){_bx=_T.offsetWidth;_by=_T.offsetHeight;if(!(_bx&&_by)&&_T.tagName=='DIV'){for(var _bE=_T.childNodes,_bF=_bE.length;--_bF>=0;){if(_bE[_bF].nodeName.charAt(0)!='#'){var _bG=_bu(_bE[_bF]);if(_bG.width||_bG.height){_bx=Math.max(_bx,_bG.right-_bv+1);_by=Math.max(_by,_bG.bottom-_bw+1);}}}}function _bH(_T){return _bI(_T,'display')=='none'||_bI(_T,'visibility')==_p;}if(_T.tagName=='A'&&_T.childNodes.length==1&&_T.childNodes[0].tagName=='IMG')_T=_T.childNodes[0];var _bJ=_bz= !_bH(_T),_bK=_T,_bL=_T;while(_bL.parentNode&&typeof _bL.parentNode!='unknown'){var _bM=_bL.offsetLeft||0,_bN=_bL.offsetTop||0,_bO=_bL.offsetWidth,
_bP=_bL.offsetHeight;if(_bz&&_bH(_bL))_bz=_f;if(_bL==_bK){_bv+=_bM+(parseInt(_bI(_bL,'borderLeftWidth'))||0);_bw+=_bN+(parseInt(_bI(_bL,'borderTopWidth'))||0);_bK=_bL.offsetParent;_bI(_bL,'position')=='fixed'&&_bD();}if(_bL!=_T&&_bL!=document.body&&_bL!=document.documentElement&&(_bL.scrollWidth>_bO||_bL.scrollHeight>_bP)){_bv-=_bL.scrollLeft;_bw-=_bL.scrollTop;if(_k){_bv+=_bL.clientLeft;_bw+=_bL.clientTop;}if(_bz)_bz=_2(_bv,_bw,_bx,_by,_bM,_bN,_bO,_bP);}_bL=_bL.parentNode;}if(_bz)_bz=_2(_bv,_bw,_bx,_by,_bA.scrollLeft,_bA.scrollTop,_bB.width,_bB.height);}return{x:_bv,y:_bw,width:_bx,height:_by,area:_bx*_by,left:_bv,top:_bw,right:_bv+_bx-1,bottom:_bw+_by-1,seen:_bz};};var _bC=_a.getDimensions=function(_T){if(_T==window){var _bA=document.documentElement;return{width:_bA.clientWidth||window.innerWidth||_bA.offsetWidth,height:_bA.clientHeight||window.innerHeight||_bA.offsetHeight};}else if(_T=_W(_T)){return{width:_T.offsetWidth||parseInt(_bI(_T,'width'))||0,height:_T.offsetHeight||parseInt(_bI(_T,'height'))||0};
}else{return{width:0,height:0};}};var _bQ={borderColor:['border','Color'],borderWidth:['border','Width'],padding:1,margin:1},_bI=_a.getStyle=function(_T,_bR){var _bS='';if(typeof _bR==_c){if(_T){var _bT=_k&&_bR=='opacity',_bU=document.defaultView,_bV=_bU&&_bU.getComputedStyle(_T,'');if(_bT)_bR='filter';if(_bV){if(!(_bS=_bV[_bR])){var _bW=_bQ[_bR];if(_bW){var _bX=_bW[0]||_bR,_bY=_bW[1]||'',_bZ=_bV[_bX+'Top'+_bY],_b0=_bV[_bX+'Right'+_bY],_b1=_bV[_bX+'Bottom'+_bY],_b2=_bV[_bX+'Left'+_bY];_bS=_bZ==_b0&&_b0==_b1&&_b1==_b2?_b2:_bZ+' '+_b0+' '+_b1+' '+_b2;}}}else{var _b3=_T.currentStyle;_bS=_b3?_b3.getAttribute(_bR):_T.style[_bR];}if(_bT){var _b4=_bS.match(/alpha\s*\(\s*opacity\s*=([^\)]*)\)/i);_bS=_b4?_b4[1]/100:1;}}}else{_bS={};if(_T)for(_bR in _bR)_bS[_bR]=_bI(_T,_bR);}return _bS;};var _b5=_a.getText=function(_T){var _b6='';if(_T=_W(_T)){function _b7(_T){if(typeof _T.innerText==_c){_b6+=_T.innerText.replace(/\r|\n|\r\n/g,'');}else if(typeof _T.textContent==_c){_b6+=_T.textContent;}else{
if(_T.nodeType==3)_b6+=_T.data;if(_T.childNodes){for(var _bF= -1,_bE=_T.childNodes,_b8=_bE.length;++_bF<_b8;)_b5(_bE[_bF]);}}}_b7(_T);}return _b6;};_a.getValue=function(_T){var _bS;if(_T=_W(_T)){if(_X(_T)){var _b9=_T.tagName;if(_b9=='TEXTAREA'){_bS=_T.value;}else if(_b9=='INPUT'){_bS=_T.type=='checkbox'?_T.checked:_T.value;}else if(_b9=='SELECT'){if(_T.multiple){_bS=[];for(var _ca= -1,_cb=_T.options,_cc=_cb.length,_cd;++_ca<_cc;)(_cd=_cb[_ca]).selected&&_bS.push(_cd.value);}else{_bS=_T.value;}}else if(_b9=='IMG'){_bS=_T.src;}else{_bS=_T.innerHTML.replace(/<br\/?>/gi,'\n').replace(/&nbsp;/g,' ');}}else{_bS=(Uize.findRecord(_T,{tagName:'INPUT',type:'radio',checked:_e})||{}).value;}}return _bS;};_a.injectHtml=function(_Q,_ce,_cf){var _cg,_ch,_ci,_cj,_ck,_cl;((_cg=_cf=='inner replace')||(_ch=_cf=='outer replace')||(_ci=_cf=='inner top')||(_cj=_cf=='outer top')||(_ck=_cf=='outer bottom')||(_cl=_e));_ce+='';_S(_Q,function(_T){var _cm=_T.childNodes;function _cn(_co){return _co&&/<script/i.test(_co);}function _cp(){
return _cn(_ce);}if((_cg||(!_cm.length&&(_ci||_cl)))&& !_cp()){_T.innerHTML=_ce;}else if(_ch&&_k&& !_cp()){_T.outerHTML=_ce;}else{if(_cg)_T.innerHTML='';var _cq=document.createElement('DIV');_cq.innerHTML=_ce;var _cr=_ci?_cm[0]:_ck?_T.nextSibling:_T,_cs=_cq.childNodes,_ct=_T.parentNode;function _cu(_T){if(_T.tagName=='SCRIPT'){var _cv=document.createElement('script');if(_T.id)_cv.id=_T.id;if(_T.type)_cv.type=_T.type;_cv.text=_T.text;if(_T.src)_cv.src=_T.src;_T.parentNode.replaceChild(_cv,_T);}else if(_cn(_T.innerHTML)){for(var _bF= -1,_cm=_T.childNodes,_cw=_cm.length;++_bF<_cw;)_cu(_cm[_bF]);}}while(_cs.length){var _cx=_cs[0];if(_cl||_cg){_T.appendChild(_cx);}else if(_ci){_cr?_T.insertBefore(_cx,_cr):_T.appendChild(_cx);}else if(_cj||_ch){_ct.insertBefore(_cx,_cr);}else if(_ck){_cr?_ct.insertBefore(_cx,_cr):_ct.appendChild(_cx);}_cu(_cx);}_ch&&_ct.removeChild(_T);}});};var _X=_a.isNode=function(_T){return!!(_T&&typeof _T=='object'&&(_T.getAttribute||_T.documentElement||(_T.self&&_T.self==_T)));};
var _bp=_a.isOnNodeTree=function(_T,_cy){_T=_W(_T);_cy=_W(_cy);while(_T){if(_T==_cy)return _e;_T=_T.parentNode;}return _f;};var _bc=_a.joinIdPrefixAndNodeId=function(_U,_v){return(_U||'')+(_U&&_v?'-':'')+_v;};_a.remove=function(_Q){_S(_Q,function(_T){_T.parentNode.removeChild(_T)});};_a.setClipRect=function(_Q,_bZ,_b0,_b1,_b2){var _cz='rect('+_bZ+'px, '+_b0+'px, '+_b1+'px, '+_b2+'px)';_S(_Q,function(_T){_T.style.clip=_cz});};var _cA=['left','top','width','height'];_a.setCoords=function(_Q,_cB){_cC(_Q,typeof _cB.length=='number'?_D(_cA,_cB):_cB);};_a.centerInWindow=function(_Q){var _cD=_bu(window);_S(_Q,function(_T){var _cE=_bC(_T);_a.setCoords(_T,{left:_cD.x+((_cD.width-_cE.width)>>1),top:_cD.y+((_cD.height-_cE.height)>>1)});});};_a.getEventAbsPos=function(_cF){var _cG=(_cF||(_cF=_t)).targetTouches;if(_cG&&_cG.length)_cF=_cG[0];if(_cF.pageX!=_b){return{left:_cF.pageX,top:_cF.pageY};}else{var _bA=_x();return{left:_cF.clientX+_bA.scrollLeft,top:_cF.clientY+_bA.scrollTop};}};
var _cH=_a.setAbsPos=function(_Q,_cI,_cJ){_cJ=typeof _cJ=='number'?{x:_cJ,y:_cJ}:(_cJ||{x:0,y:0});var _bA=document[_l?'body':'documentElement'],_cK=_bC(window);_S(_Q,function(_T){function _cL(_cM,_cN,_cO,_cP){var _cQ=_cI[_cM],_cR=_cJ[_cP],_cS=_cQ-_bA[_cN],_cT=_cR+_cE[_cO];return(_cQ+(_cS+_cT>_cK[_cO]?Math.max(-_cT,-_cS):_cR));}var _cE=_bC(_T);_cC(_T,{left:_cL('left','scrollLeft','width','x'),top:_cL('top','scrollTop','height','y'),right:'auto',bottom:'auto'});});};_a.setAbsPosAdjacentTo=function(_Q,_cU,_cV){_cU=_W(_cU);var _cW=_bu(_cU),_cX=_cW.width/2,_cY=_cW.height/2,_cZ=_cV=='x'? -1:1;if(!_cX&& !_cY)_cW=_a.getEventAbsPos();_S(_Q,function(_T){_cH(_T,{left:_cW.left+_cX,top:_cW.top+_cY},{x:-_cX*_cZ,y:_cY*_cZ});});};_a.setInnerHtml=function(_Q,_co){_co+='';_S(_Q,function(_T){_T.innerHTML=_co});};var _c0={};_a.setOpacity=function(_Q,_c1){_c0.opacity=_c1;_cC(_Q,_c0);};_a.setProperties=function(_Q,_bd){_S(_Q,function(_T){_q(_T,_bd)});};var _cC=_a.setStyle=function(_Q,_bd){_S(_Q,function(_T){var _c2=_T.style,_c3;
if(_k&&'opacity'in _bd)_c2.filter=(_c3=Math.round(_bd.opacity*100))<100?'alpha(opacity='+_c3+')':'';for(var _bR in _bd)_c2[_bR]=(typeof(_c3=_bd[_bR])=='object'&&_c3?(_c3=_c3.valueOf()):_c3)!=_b?(typeof _c3=='number'&&_bR!='opacity'&&_bR!='zIndex'?Math.round(_c3)+'px':_c3+''):'';});};_a.setValue=function(_Q,_bS){_bS+='';_S(_Q,function(_T){var _b9=_T.tagName,_c4=_T.readOnly;if(_c4)_T.readOnly=_f;if(_b9=='TEXTAREA'){_T.value=_bS;}else if(_b9=='INPUT'){var _c5=_T.type;if(_c5=='text'||_c5==_p||_c5=='password'){_T.value=_bS;}else if(_c5=='checkbox'){_T.checked=_bS=='true';}else if(_c5=='radio'){_T.checked=_T.value==_bS;}}else if(_b9=='SELECT'){if(!_bS){_T.selectedIndex= -1;}else{var _cb=_T.options;if(_T.multiple&&(_bS=='*'||_bS.indexOf(',')> -1)){var _c6;if(_bS!='*'){_c6={};for(var _F=_bS.split(','),_G=_F.length;--_G>=0;)_c6[_F[_G]]=1;}for(var _ca=_cb.length,_cd;--_ca>=0;)(_cd=_cb[_ca]).selected= !_c6||_c6[_cd.value];}else{_T.selectedIndex=Uize.findRecordNo(_cb,{value:_bS},_T.selectedIndex);}}}else if(_b9=='IMG'){
if(_bS)_T.src=_bS;}else{_b9=='PRE'&&_k?(_T.innerText=_bS):(_T.innerHTML=_bS.replace(/</g,'&lt;').replace(/\n/g,'<br/>'));}if(_c4)_T.readOnly=_c4;});};_a.show=function(_Q,_c7){_cC(_Q,{visibility:_c7||_c7===_b?'inherit':_p});};_a.showClickable=function(_Q,_c8){_cC(_Q,{cursor:_c8||_c8===_b?(_k?'hand':'pointer'):'default'});};var _c9=_a.unwire=function(_Q,_da,_db,_dc){if(typeof _da=='object'&&_da&& !_da.virtualDomEvent){for(var _C in _da)_c9(_Q,_C,_da[_C],_db);}else{_a.unwireEventsByOwnerId(_dc,_Q!==_b||_da!=_b||_db!=_b?{node:_Q,eventName:_da,handler:_db}:_b);}};_a.unwireEventsByOwnerId=function(_dd,_de){var _df=_J[_dd=_dd||''];if(_df){function _dg(_dh){if(_dh!==_g){var _di=_de&&_de.eventName,_dj=_de&&_de.handler,_dk=_dh||_di||_dj;if(_di&&_di.charCodeAt)_di=_B(_di);for(var _dl=_df.length;--_dl>=0;){var _dm=_df[_dl],_dn=_I[_dm],_T=_dn._T,_C=_dn._C;if(!_dk||((!_dh||_dh==(_dn._do||_T))&&(!_di||_di==_C)&&(!_dj||_dj==_dn._dp))){_dk&&_df.splice(_dl,1);if(_dn._dq){_a.unwireEventsByOwnerId(_dn._dq)}else{try{_T==window
?_dr.unwire(_C,_dn._ds):_k?_T.detachEvent('on'+_C,_dn._ds):_T.removeEventListener(_C,_dn._ds,_f);}catch(_dt){}}delete _I[_dm];}}(_dk&&_df.length)||delete _J[_dd];}}_de&&_de.node!==_b?_S(_de.node,_dg):_dg();}};var _du=_y(function(_dm){return(function(_s){var _dn=window.Uize&&Uize.Node._I[_dm];return _dn&&_dn._dp.call(_dn._T,_s.windowEvent);});}),_dv=_y(function(_dm){return(function(_s){var _dn=window.Uize&&Uize.Node._I[_dm];return _dn&&_dn._dp.call(_dn._T,_s||window.event);});}),_dw={click:_dv,mouseover:_y(function(_dm){return(function(_s){var _dn=window.Uize&&Uize.Node._I[_dm],_dx=(_s||(_s=window.event)).fromElement||_s.relatedTarget;if(_dn){if(_dx){try{if(!_dx.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dx,_dn._T))_dx=null;}catch(_dt){_dx=null;}}if(!_dx){Uize.Node._r(_s);return _dn._dp.call(_dn._T,_s);}}});}),mouseout:_y(function(_dm){return(function(_s){var _dn=window.Uize&&Uize.Node._I[_dm],_dy=(_s||(_s=window.event)).toElement||_s.relatedTarget;if(_dn){if(_dy){try{
if(!_dy.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dy,_dn._T))_dy=null;}catch(_dt){_dy=null;}}if(!_dy)return _dn._dp.call(_dn._T,_s);}});}),mousedown:_dv,mouseup:_dv};_a.wireEvent=_a.wireEvents=_a.wire=function(_Q,_C,_dp,_dd){if(!_C)return;if(_dd==_b)_dd='';var _dz;if(_C.charCodeAt)_C=_B(_C);if(typeof _C=='object'&& !(_dz= !!_C.virtualDomEvent)){_dd=arguments[2]||'';for(var _s in _C)_a.wire(_Q,_s,_C[_s],_dd);return;}_S(_Q,function(_T){var _b9=_T.tagName;(_J[_dd]||(_J[_dd]=[])).push(_K);var _ds=(_dz?_a.returnFalse:_T==window?_du:_dw[_C]||_dv)(_K);var _dn=_I[_K++]={_T:_T,_C:_C,_dp:_dp,_ds:_ds};if(_o&&_b9=='BODY'&&_C=='scroll'){_dn._do=_T;_T=_dn._T=document;}if(_ds){var _dA='on'+_C;_T==window?_dr.wire(_C,_ds):_k?_T.attachEvent(_dA,_ds):_T.addEventListener(_C,_ds,_f);if(_b9=='A'&&(_C=='mousedown'||_C=='click')&& !_T[_dA])_T[_dA]=_a.returnFalse;}else if(_dz){_C.wire(_T,_dp,_dn._dq=Uize.getGuid());}});};_a.returnFalse=new Function('return false');_a.returnTrue=new Function('return true');_a.isIe=_k;
_a.isSafari=_l;_a.isMozilla=_m;if(_h){_a.wire(document.documentElement,'mousemove',_r);var _dr=new Uize,_dB=setTimeout(function(){_dr.fire('load')},15000);function _dC(_dD){var _dE='on'+_dD,_dF=window[_dE]||_a.returnFalse;window[_dE]=function(_s){_dD=='load'&&clearTimeout(_dB);_dF.call(window,_s||(_s=window.event));_dr.fire({name:_dD,windowEvent:_s});};}for(var _dD in{focus:1,blur:1,load:1,beforeunload:1,unload:1,resize:1,scroll:1})_dC(_dD);;}return _a;}});


Uize.module({name:'Uize.Widget',required:'Uize.Node',builder:function(b_a){var b_b=null,b_c=true,b_d=false,b_e='string',b_f='function',b_g='concatenated',b_h,b_i=Uize.Node,b_j=b_i.doForAll,b_k=b_i.isNode,b_l=b_i.getById;var b_m=b_a.subclass(function(){this.children=this.b_n={};}),b_o=b_m.prototype;b_o.b_p=function(){if(window['$'+this.b_q]&&(!this.parent||this.b_q!=this.parent.b_q)){var b_r='$'+this.b_q;this.set(window[b_r]);window[b_r]=b_h;}};b_o.b_s=function(b_t,b_u,b_v,b_w){return((b_w==b_g|| !b_w)&&b_t!=b_h?(b_t+(b_v!==''?'_':'')+b_v):(b_w=='same as parent'?b_t:b_u));};var b_x={b_y:b_d,b_z:b_c};b_o.b_A=function(){(this.b_B=='inherit'?(this.parent||b_x).b_y:this.b_B)!=this.b_y&&this.set({b_y:!this.b_y});};b_o.b_C=function(){(this.b_D=='inherit'?(this.parent||b_x).b_z:this.b_D)!=this.b_z&&this.set({b_z:!this.b_z});};b_o.b_E=function(b_F,b_G,b_H){var b_I='show'+b_m.capFirstChar(b_F);this.getProvider(b_I)?this.callInherited(b_I)(b_G):setTimeout(function(){var b_J=b_H();
(b_G.callback||(b_J?b_G.yesHandler:b_G.noHandler)||function(){})(b_J)},0);};b_o.confirm=function(b_G){this.b_E('confirm',b_G,function(){return confirm(b_G.message)});};b_o.showInform=b_o.showConfirm=b_h;b_o.inform=function(b_G){this.b_E('inform',b_G,function(){alert(b_G.message);return b_c});};b_o.localize=function(b_K,b_L,b_M){var b_N,b_O=this;while(!(b_N=b_O.b_P?b_O.b_P[b_K]:b_h)&&(b_O=b_O.parent));return(typeof b_N==b_f?b_N.call(this,b_L):b_m.substituteInto(b_N,b_L,b_M||'{KEY}'));};b_o.buildHtml=function(b_Q){var b_R=this,b_S=b_R.b_S;if(b_S!=b_h){var b_T=b_R.b_U||b_R.getNode('shell')||b_R.getNode();if(b_S===b_c){b_S=b_R.b_S=Uize.Template&&b_T?{process:Uize.Template.compile((b_i.find({root:b_T,tagName:'SCRIPT',type:'text/jst'})[0]||b_T).innerHTML,{openerToken:'[%',closerToken:'%]'})}:b_h;if(!b_S)return;}b_R.b_q||b_R.set({b_q:b_R.instanceId});var b_V=b_m.copyInto({pathToResources:b_R.Class.pathToResources,blankGif:b_m.getBlankImageUrl()},b_Q||b_R.get()),b_W=typeof b_S;b_i.injectHtml(b_T||document.body,
b_W!=b_e&&typeof b_S.process==b_f?b_S.process.call(b_R,b_V):b_m.substituteInto(b_W==b_f?b_R.b_S(b_V):b_S,b_V),b_R.b_X||(b_T?'inner replace':'inner bottom'));b_R.b_Y=b_b;b_R.set({b_Z:b_c});}};b_o.wired=function(){return this.isWired};function b_0(b_1,b_2){b_o[b_1+'Node'+b_2]=new Function('arguments.length'+'?(arguments[0]=this.getNode(arguments[0]))'+':(arguments[arguments.length++]=this.getNode());'+'return Uize.Node.'+b_1+b_2+'.apply(0,arguments)');}b_o.getNode=function(b_3){if(b_3==b_b){if(b_3===b_b)return b_b;b_3='';}var b_R=this;if(b_R.b_4&&typeof b_3==b_e){var b_5=b_R.b_4[b_3];if(b_5!==b_h)b_3=b_5;}if(typeof b_3==b_e){return b_l(b_3,b_R.b_q,b_R.b_Y||(b_R.b_Y={}));}else if(b_k(b_3)){return b_3;}else{var b_6=b_b;b_j(b_3,function(b_7){(b_6||(b_6=[])).push(b_7)},b_R.b_q,b_R.b_Y||(b_R.b_Y={}));return b_6;}};b_0('get','Style');b_0('get','Value');b_o.flushNodeCache=function(b_8){if(this.b_Y)b_8==b_h?(this.b_Y=b_b):delete this.b_Y[b_8];};b_o.globalizeNode=function(b_9){var b_R=this,b_ba=document.body;b_j(
b_R.getNode(b_9),function(b_7){if(b_7.parentNode!=b_ba){(b_R.b_bb||(b_R.b_bb=[])).push(b_7);b_i.setStyle(b_7,{position:'absolute',left:-10000,top:-10000});b_ba.appendChild(b_7);}});};b_0('display','');b_0('inject','Html');b_o.removeNode=function(b_9){b_i.remove(this.getNode(b_9));this.flushNodeCache(b_9);};b_0('set','Properties');b_0('set','Opacity');b_0('set','Style');b_0('set','ClipRect');b_0('set','InnerHtml');b_0('set','Value');b_0('show','');b_o.wireNodeEvent=b_o.wireNodeEvents=b_o.wireNode=function(b_9,b_bc,b_bd){arguments.length==3?b_i.wire(this.getNode(b_9),b_bc,b_bd,this.instanceId):b_i.wire(this.getNode(b_9),b_bc,this.instanceId);};b_o.unwireNodeEvent=b_o.unwireNode=function(b_9,b_bc,b_bd){if(b_9!==b_h)b_9=this.getNode(b_9);arguments.length==2&&typeof b_bc=='object'&&b_bc&& !b_bc.virtualDomEvent?b_i.unwire(b_9,b_bc,this.instanceId):b_i.unwire(b_9,b_bc,b_bd,this.instanceId);};b_o.unwireNodeEventsByMatch=function(b_9,b_be){this.unwireNode(b_9,(b_be||(b_be={})).eventName,b_be.handler);};
b_o.addChild=function(b_v,b_bf,b_bg){if(!b_bg)b_bg={};var b_R=this,b_q=b_R.b_q,b_bh=b_m.isInstance(b_bf)?b_bf:b_b,b_u='idPrefix'in b_bg?b_bg.idPrefix:b_bg.node,b_bi=b_bg.idPrefixConstruction;b_bg.parent=b_R;if(b_v==b_h)b_v=b_bg.name;if(b_bh){if(b_v==b_h)b_v=b_bh.b_bj;if(b_u==b_h)b_u=b_bh.b_q;if(!b_bi)b_bi=b_bh.b_w;}if(!b_bi)b_bi=b_u==b_h?b_g:'explicit';b_bg.idPrefixConstruction=b_bi;b_bg.idPrefix=b_R.b_s(b_q,b_u,b_v,b_bi);b_bg.name=b_v;b_bh&&b_bh.set(b_bg);return b_R.b_n[b_v]=b_bh||new b_bf(b_bg);};b_o.removeChild=function(b_bk){var b_n=this.b_n,b_v=typeof b_bk==b_e||b_m.isNumber(b_bk)?b_bk:b_bk.b_bj,b_bh=b_n[b_v];if(b_bh){b_bh.unwireUi();delete b_bh.parent;delete b_n[b_v];}};b_o.getProvider=function(b_bl){var b_bm=this,b_bn;while(((b_bn=b_bm.get(b_bl))==='inherit'||b_bn===b_h)&&(b_bm=b_bm.parent));return b_bm;};b_o.getInherited=function(b_bl){var b_bo=this.getProvider(b_bl);return b_bo?b_bo.get(b_bl):b_h;};b_o.setInherited=function(b_bg){var b_bo;for(var b_bp in b_bg){if(b_bo=this.getProvider(b_bp))
b_bo.set(b_bp,b_bg[b_bp]);}};b_o.callInherited=function(b_bl){var b_R=this;return(function(){var b_bo=b_R.getProvider(b_bl),b_6;if(b_bo){var b_bq=b_bo.get(b_bl);if(typeof b_bq==b_f)b_6=b_bq.apply(b_bo,arguments);}return b_6;});};b_o.kill=function(){b_m.callOn(this.b_n,'kill');b_a.prototype.kill.call(this);};b_o.insertOrWireUi=function(){this.b_Z?this.wireUi():this.insertUi();};b_o.insertUi=function(){this.buildHtml();this.wireUi();};b_o.removeUi=function(){this.unwireUi();this.removeNode();b_i.remove(this.b_bb);this.b_bb=b_h;b_m.callOn(this.b_n,'removeUi');this.set({b_Z:b_d});};b_o.updateUi=function(){};b_o.wireUi=function(){if(!this.isWired){this.b_p();this.set({wired:b_c});var b_n=this.b_n;for(var b_v in b_n)b_n[b_v].insertOrWireUi();this.updateUi();}};b_o.unwireUi=function(){if(this.isWired){this.b_Y=b_b;this.unwireNode();b_m.callOn(this.b_n,'unwireUi');this.set({wired:b_d});}};b_m.getBlankImageUrl=function(){return Uize.pathToResources+'Uize/blank.gif';};b_m.spawn=function(b_bg,b_br){var b_R=this,b_bs=[],
b_bm,b_bt=b_br&&b_br.b_q?b_br.b_q+'_':'',b_bu=b_bt.length;b_j(Uize.Node.find(b_bg.idPrefix),function(b_7){b_bg.idPrefix=b_7;b_br?(b_bm=b_br.addChild(b_7.id.slice(0,b_bu)==b_bt?b_7.id.slice(b_bu):'generatedChildName'+b_m.getGuid(),b_R,b_bg)):(b_bm=new b_R(b_bg)).insertOrWireUi();b_bs.push(b_bm);});return b_bs;};b_m.registerProperties({b_Z:{name:'built',value:b_c},b_B:{name:'busy',onChange:b_o.b_A,value:'inherit'},b_y:{name:'busyInherited',onChange:function(){b_m.callOn(this.b_n,b_o.b_A)},value:b_d},b_U:'container',b_D:{name:'enabled',onChange:b_o.b_C,value:'inherit'},b_z:{name:'enabledInherited',onChange:function(){b_m.callOn(this.b_n,b_o.b_C)},value:b_c},b_S:'html',b_q:{name:'idPrefix|node',conformer:function(b_q){return b_k(b_q)?(b_q.id||(b_q.id=Uize.getGuid())):b_q;},onChange:function(){var b_R=this,b_q=b_R.b_q;b_R.b_Y=b_b;if(b_q!=b_h){b_R.b_p();var b_n=b_R.b_n,b_bh;for(var b_v in b_n)(b_bh=b_n[b_v]).set({b_q:b_R.b_s(b_q,b_bh.b_q,b_v,b_bh.b_w)});if(b_R.isWired){b_R.set({wired:b_d});b_R.wireUi();}}}},
b_w:'idPrefixConstruction',b_X:'insertionMode',b_P:'localized',b_bj:'name',b_4:'nodeMap',isWired:{name:'wired',value:b_d}});if(typeof navigator!='undefined'){function b_bv(b_bw,b_bx){b_i.wire(window,b_bw,function(){b_m.fire(b_bx)});}b_bv('load','Document Loaded');b_bv('unload','Document Unload');b_bv('resize','Window Resized');b_bv('scroll','Window Scrolled');}return b_m;}});


Uize.module({name:'Uize.Widget.Page',builder:function(c_a){var c_b=true,c_c=false,c_d;var c_e=c_a.subclass(null,function(){c_e.xDeferredLinks&&this.wireDeferredLinks()}),c_f=c_e.prototype;c_f.c_g=function(c_h,c_i,c_j){var c_k=this;c_k.useDialog({component:c_k.c_l.component,widgetClassName:c_k.c_l.widgetClassName||'Uize.Widget.Dialog.Confirm',widgetProperties:{name:'confirmDialog',title:c_j.title||'',message:(c_j.message+'').replace(/\n/g,'<br/>'),mode:c_h,state:c_j.state||c_i,okText:c_j.okText||null,cancelText:c_j.cancelText||null},submitHandler:function(c_m){var c_n=c_j.callback||(c_m?c_j.yesHandler:c_j.noHandler);c_n&&c_n(c_m);}});};c_f.useDialog=function(c_j){var c_k=this,c_o=c_j.widgetProperties,c_p=c_o.parent||c_k,c_q=c_o.name,c_r=c_p.children[c_q],c_s=c_j.component,c_t;if(c_s){var c_u=c_o.idPrefix||(c_p.get('idPrefix')+'_'+c_q);c_t={name:c_s.name,rootNodeId:c_u,params:c_e.copyInto({idPrefix:c_u},c_s.params)};}function c_v(c_w){var c_x=c_k.get('productType');c_r.fire({name:'Track Event',
extra:c_w+(c_x?(' ('+c_x+')'):''),bubble:c_b});}function c_y(c_z){setTimeout(function(){function c_A(c_B,c_C){var c_n=c_j[c_B];c_n&&c_n.apply(0,c_C);}function c_D(c_E){var c_C=[c_E];c_A(c_E.name.toLowerCase()+'Handler',c_C);c_A('dismissHandler',c_C);}c_r.unwire(c_r.eventHandlersForUseDialog||{});c_r.eventHandlersForUseDialog={'Submission Complete':function(c_E){c_A('submitHandler',[c_E.result,c_E])},Close:c_D,Cancel:c_D};c_r.wire(c_r.eventHandlersForUseDialog);c_r.set(c_o);c_r.set({shown:c_b});c_v(c_z);},0);}if(c_r&&(c_r.componentProfile==c_t||Uize.Data.identical(c_r.componentProfile,c_t))){c_y('subsequent');}else{var c_F=c_t&& !!c_r;if(c_F){c_r.removeUi();c_p.removeChild(c_q);}function c_G(){var c_H=c_j.widgetClassName;Uize.module({required:c_H,builder:function(){c_r=c_p.addChild(c_q,eval(c_H),c_o);c_r.componentProfile=c_t;c_r.wire(c_j.widgetEventHandlers);c_r.insertOrWireUi();c_y(c_F?'refetched':'initial');}});}c_t?c_k.loadComponentIntoNode({rootNodeId:c_t.rootNodeId,
componentParams:c_e.copyInto({cp:c_t.name},c_t.params),injectMode:'inner bottom',alwaysReplace:c_c,callback:c_G}):c_G();}};c_f.wireUi=function(){var c_k=this;if(!c_k.isWired){var c_I=c_k.get('idPrefix');function c_J(c_K,c_L){var c_M,c_N;for(var c_O in c_L)(typeof(c_M=c_K[c_O])=='object'&&typeof(c_N=c_L[c_O])=='object'&&c_M&&c_N)?c_J(c_M,c_N):(c_K[c_O]=c_L[c_O]);}var c_P={},c_Q=c_c,c_R='$'+c_I+'_',c_S=c_R.length,c_T;for(var c_O in window){if(c_O.charAt(0)=='$'&&c_O.substr(0,c_S)==c_R&&typeof(c_T=window[c_O])=='object'&&c_T&&c_T.widgetClass){c_Q=c_b;for(var c_U= -1,c_V=c_P,c_W=c_O.substr(c_S).split('_'),c_X=c_W.length;++c_U<c_X;){var c_Y=c_W[c_U],c_Z=c_V[c_Y];if(c_U<c_X-1){if(!c_Z)c_Z=c_V[c_Y]={};c_V=c_Z.children||(c_Z.children={});}else{c_Z?c_J(c_Z,c_T):(c_V[c_Y]=c_T);window[c_O]=c_d;}}}}if(c_Q){function c_0(c_1,c_2){function c_3(c_4,c_5,c_6){var c_7=c_6.children,c_8=c_1(c_4,c_5,c_6);c_7&&c_9(c_8,c_7);c_2&&c_2(c_8);}function c_9(c_4,c_ba){for(var c_5 in c_ba)c_3(c_4,c_5,c_ba[c_5]);}c_9(c_k,c_P);}var c_bb={},
c_bc=[];c_0(function(c_4,c_5,c_6){var c_bd=c_6.widgetClass;if(c_bd&& !c_bb[c_bd]){c_bb[c_bd]=1;c_bc.push(c_bd);}});Uize.module({required:c_bc,builder:function(){c_0(function(c_4,c_5,c_6){var c_8=c_4.children[c_5],c_bd=c_6.widgetClass||Uize.Widget;delete c_6.widgetClass;delete c_6.children;c_8?c_8.set(c_6):(c_8=c_5.charCodeAt(0)==36&&c_5.charCodeAt(1)==36?eval(c_bd).spawn(c_6,c_4):c_4.addChild(c_5,eval(c_bd),c_6));return c_8;},c_k.isWired?function(c_8){c_e.callOn(c_8,'insertOrWireUi')}:0);}});}c_a.prototype.wireUi.call(c_k);}};var c_be={yes:1,on:1,1:1,'true':1};c_e.launchPopup=c_f.launchPopup=function(c_j){if(!c_j)c_j={};if(c_j.width==c_d)c_j.width=850;if(c_j.height==c_d)c_j.height=600;var c_bf=window.screen;if(c_j.left==c_d)c_j.left=Math.max((c_bf.width-c_j.width-10)>>1,0);if(c_j.top==c_d)c_j.top=Math.max((c_bf.height-c_j.height-40)>>1,0);function c_bg(c_bh){return c_bh+'='+c_j[c_bh];}function c_bi(c_bh,c_bj){return(c_bh+'='+(c_be[c_j[c_bh]==c_d?c_bj:c_j[c_bh]+'']?'yes':'no'));}var c_bk=window.open(
c_j.url||'',c_j.name==c_d?'popupWindow':c_j.name,[c_bg('width'),c_bg('height'),c_bg('top'),c_bg('left'),c_bi('toolbar',0),c_bi('location',0),c_bi('directories',0),c_bi('status',0),c_bi('menubar',0),c_bi('scrollbars',1),c_bi('resizable',1)].join(','));c_bk&&c_bk.focus();return c_bk;};c_e.registerProperties({c_l:{name:'confirmDialog',value:{}}});c_e.set({idPrefix:'page'});c_f.showConfirm=function(c_j){this.c_g('confirm','confirm',c_j);};c_f.showInform=function(c_j){this.c_g('alert','info',c_j);};return c_e;}});


Uize.module({name:'UizeDotCom.Templates'});


Uize.module({name:'UizeDotCom.Templates.WidgetToGoTitle',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="widgetHeader">\r\n	<div id="',input.idPrefix,'_menu_selector" title="Click to show/hide widget options..." class="widgetTitle">\r\n		<div class="logo"></div>\r\n		<div class="textShadow">',input.title,'</div>\r\n		<div class="textHighlight">',input.title,'</div>\r\n		<div class="textMain">',input.title,'</div>\r\n	</div>\r\n	<div id="',input.idPrefix,'_menu-palette" class="subMenuShell">\r\n		<a id="',input.idPrefix,'_menu-getThisWidget" href="javascript://" class="subMenuItem">GET THIS WIDGET</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-aboutThisWidget" href="javascript://" class="subMenuItem">About This Widget</a>\r\n		<a id="',input.idPrefix,'_menu-openInNewWindow" href="javascript://" class="subMenuItem">Open Widget in New Window</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-moreWidgets"  href="javascript://" class="subMenuItem">More UIZE Widgets...</a>\r\n		<a id="',input.idPrefix,'_menu-uize" href="javascript://" class="subMenuItem">UIZE JavaScript Framework</a>\r\n	</div>\r\n</div>\r\n\r\n');
return output.join('');};_a.input={idPrefix:'string',title:'string'};return _a;}});


Uize.module({name:'Uize.Fade',builder:function(b_a){var b_b,b_c='object',b_d=Uize.constrain;var b_e={},b_f=[],b_g=false,b_h;function b_i(){if((b_g= !!b_f.length)!= !!b_h)b_h=b_g?setInterval(b_j,10):clearInterval(b_h);}function b_j(){for(var b_k= -1,b_l;++b_k<b_f.length;)(b_l=b_f[b_k]).b_m?b_l.b_j():b_f.splice(b_k--,1);b_i();}function b_n(b_o){return b_o}var b_p=b_a.subclass(),b_q=b_p.prototype;b_q.b_r=function(){var b_s=this,b_o=b_t(b_s.b_u,b_s.b_v,b_s.b_w,b_s.b_x,b_s.b_y,b_s.b_o);if(b_o!=b_e)b_o!=b_s.b_o?b_s.set({b_o:b_o}):b_s.fire('Changed.value');};b_q.b_j=function(){var b_z=Math.min(((Date.now?Date.now(): +new Date)-this.b_A)/this.b_B,1);this.set({b_w:this.b_C?1-b_z:b_z});if(b_z==1){this.stop();this.fire('Done');}};b_q.stop=function(){this.set({b_m:false});};b_q.start=function(b_D){this.stop();this.set(b_p.copyInto({b_m:true},b_D));};var b_t=b_p.blendValues=function(b_E,b_F,b_G,b_x,b_y,b_H){if(b_E===b_F){return b_H!==b_b&&b_E===b_H?b_e:b_E;}else{if(b_y&&typeof b_y=='function'){b_G=b_y(b_G);b_y=b_b;}
if(typeof b_E==b_c&&b_E&& !(b_E instanceof RegExp)){var b_I=b_H&&typeof b_H==b_c,b_J=b_x&&typeof b_x==b_c,b_K=b_y&&typeof b_y==b_c,b_L=b_I?b_H:b_p.isArray(b_E)?[]:{},b_M;for(var b_N in b_E){var b_O=b_t(b_E[b_N],b_F[b_N],b_G,b_J?b_x[b_N]:b_x,b_K?b_y[b_N]:b_y,b_M=b_L[b_N]);if(b_I)b_I=b_O==b_e||(typeof b_O!=b_c&&b_O==b_M);if(b_O!=b_e)b_L[b_N]=b_O;}return b_I?b_e:b_L;}else{var b_L= !b_G?b_E:b_G==1?b_F: !b_x?b_E+(b_F-b_E)*b_G:b_G>0&&b_G<1?b_d(b_E+Math.round((b_F-b_E)*b_G/b_x)*b_x,b_E,b_F):b_E+Math.round((b_F-b_E)*b_G/b_x)*b_x;return b_H!==b_b&&b_L===b_H?b_e:b_L;}}};b_p.celeration=function(b_P,b_Q){var b_R=1-(b_P=b_P||0)-(b_Q=b_Q||0),b_S=2/(1+b_R),b_T=b_P?b_S/b_P:0,b_U=b_T/2,b_V=b_Q? -b_S/b_Q:0,b_W=b_V/2,b_X=b_P*b_P,b_Y;return(b_R>=1?b_n:function(b_o){return((b_o=(b_P?b_d(b_o*b_o,0,b_X)*b_U:0)+(b_R?b_S*b_d(b_o-b_P,0,b_R):0)+(b_Q?((b_S+(b_Y=b_d(b_o-b_P-b_R,0,b_Q))*b_W)*b_Y):0))>1?1:b_o);});};function b_Z(){this.set({b_y:this.b_P||this.b_Q?b_p.celeration(this.b_P,this.b_Q):null});}function b_0(){this.b_o=null;
this.b_r();}b_p.registerProperties({b_P:{name:'acceleration',onChange:b_Z},b_y:{name:'curve',onChange:b_0},b_Q:{name:'deceleration',onChange:b_Z},b_B:{name:'duration',value:2000},b_v:{name:'endValue',onChange:b_0,value:100},b_m:{name:'inProgress',onChange:function(){var b_s=this;if(b_s.b_m){b_s.b_A=Date.now?Date.now(): +new Date;b_s.fire('Start');b_s.b_o=b_s.b_w=null;b_s.b_j();b_f.push(b_s);b_i();}},value:false},b_w:{name:'progress',onChange:b_q.b_r,value:0},b_C:'reverse',b_u:{name:'startValue',onChange:b_0,value:0},b_x:'quantization',b_o:{name:'value',value:0}});return b_p;}});


Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;function c_h(){if(c_g.isWired){c_g.c_i()||c_g.set({c_j:''});c_g.c_h();}}c_g.wire({'Changed.busyInherited':c_h,'Changed.enabledInherited':c_h});}),c_k=c_f.prototype;var c_l,c_m={},c_n={grayed:16,'':8,over:4,active:2,playing:1},c_o='(Grayed|Over|Active|Playing)',c_p=new RegExp(c_o),c_q=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_o+'))','g'),c_r=new RegExp('\\S*'+c_o+'\\b','g'),c_s=/\b(disabled|over|active|playing)\b/,c_t={},c_u={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click']};c_k.c_v=c_d;c_k.c_i=function(){return(this.get('enabledInherited')&& !this.get('busyInherited')&&(!this.c_w||this.c_x));};c_k.c_y=function(){this.c_z!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_z);};var c_h=c_k.c_h=function(){var c_g=this;if(c_g.isWired){var c_A=c_g.c_A,
c_B=c_g.get('enabledInherited'),c_C=c_g.get('busyInherited'),c_D=(!c_B?16:0)|(!c_g.c_j||c_C?8:0)|(c_g==c_l?4:0)|(c_g.c_j=='down'||c_g.c_w?2:0)|(c_g.c_E?1:0),c_F=c_g.c_G[c_D];if(c_F==c_b){for(var c_H= -1,c_I=c_g.c_I,c_J=c_I.length;++c_H<c_J;){var c_K=c_I[c_H];if(c_D&c_n[c_K]){c_F=c_K;break;}}c_g.c_G[c_D]=c_F;}if(c_g.c_L=='classes'){var c_M=c_A.className,c_N='';if(c_g.c_O=='disambiguated'){var c_P=c_g.c_P;if(c_P==c_b){var c_Q=c_M.match(c_q);if(c_Q){c_P=c_Q[c_Q.length-1].split(' ',2)[0];}else{c_Q=c_M.replace(c_r,'').match(/(\S+)\s*$/);if(c_Q)c_P=c_Q[c_Q.length-1];}if(c_g.c_P=c_P=c_P||'')c_g.c_R=c_t[c_P]||(c_t[c_P]=new RegExp(c_P+'(\\s+'+c_P+c_o+')?'));}var c_S=c_F?' '+c_P+c_f.capFirstChar(c_F):'';c_N=c_P?c_M.replace(c_g.c_R,c_P+c_S):c_M.replace(c_p,'')+c_S;}else{var c_T=c_F=='grayed'?'disabled':c_F;c_N=c_s.test(c_M)?c_M.replace(c_s,c_T):c_M+(c_T?' ':'')+c_T;}if(c_N!=c_M)c_A.className=c_N;}else if(c_g.c_L=='frames'){c_g.c_U.style.top='-'+(c_g.c_V.c_W[c_F]*c_g.c_X.height)+'px';}if(c_g.c_Y&&Uize.Tooltip){
var c_Z=c_g.c_j=='over'&&c_B&& !c_g.c_w;c_Z!=c_g.c_v&&Uize.Tooltip.showTooltip(c_g.c_Y,c_g.c_v=c_Z);}c_g.get('busyInherited')?c_e.setStyle(c_A,{cursor:'wait'}):c_e.showClickable(c_A,c_g.c_i());}};c_k.c_0=function(c_1){var c_g=this;if(c_g.isWired){var c_2=c_1.type,c_3=c_2=='click',c_i=c_g.c_i();if(!c_g.c_4){c_g.c_4=c_c;function c_0(c_1){c_g.c_0(c_1)}c_g.wireNode(c_g.c_A,{mouseout:c_0,mousedown:c_0,mouseup:c_0});}if(c_3)c_1.cancelBubble=c_c;if(c_i){var c_5=c_u[c_2];c_g.set({c_j:c_5[0]});c_g.fire({name:c_5[1],domEvent:c_1});}}};c_k.updateUi=function(){this.c_h();this.c_y();};c_k.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.c_U=c_b;var c_A=c_g.c_A=c_g.getNode();if(c_A){var c_6=c_A.childNodes;if(c_6.length&&(c_6.length>1||c_6[0].nodeType!=3)&&(c_g.c_U=c_g.getNode('frames'))){c_g.c_L='frames';c_g.c_X=c_e.getDimensions(c_g.c_U.parentNode);}if(c_g.c_7&&c_A.tagName=='A'&& !c_A.onclick)c_A.onclick=c_e.returnTrue;function c_0(c_1){c_g.c_0(c_1)}c_g.wireNode(c_A,{mouseover:c_0,click:c_0});
c_a.prototype.wireUi.call(c_g);}}};c_f.addChildButton=function(c_8,c_9){var c_g=this,c_ba;function c_bb(){c_ba.wire('Click',function(c_bc){if(c_9)typeof c_9=='string'?c_g.fire(c_9):c_9(c_bc);c_g.fire(c_bc);});}if(c_g==c_f){c_ba=new c_f({idPrefix:c_8,name:c_8,c_7:c_c});c_bb();(window[c_ba.instanceId]=c_ba).wireUi();}else{c_ba=c_g.children[c_8];if(!c_ba){c_ba=c_g.addChild(c_8,c_f);c_bb();}}return c_ba;};c_f.registerProperties({c_x:{name:'clickToDeselect',onChange:c_h,value:c_d},c_O:{name:'classNamingForStates',value:'disambiguated'},c_V:{name:'frameOrder',onChange:function(){var c_V=this.c_V;if(!c_V.c_W){for(var c_bd= -1,c_be=c_V.length,c_W=c_V.c_W={};++c_bd<c_be;)c_W[c_V[c_bd]]=c_bd;}},value:['grayed','','over','active','playing']},c_7:{name:'followLink',value:c_d},c_L:{name:'mode',value:'classes'},c_E:{name:'playing',onChange:c_h,value:c_d},c_w:{name:'selected',onChange:c_h,value:c_d},c_j:{name:'state',onChange:function(){var c_g=this;if(!c_g.c_j){if(c_l==c_g)c_l=c_b;}else if(c_g.c_j=='over'){
c_l&&c_l!=c_g&&c_l.set({c_j:''});c_l=c_g;}c_g.isWired&&c_g.c_h();},value:''},c_I:{name:'statePrecedence',onChange:function(){var c_g=this,c_bf=c_g.c_I.c_bg||(c_g.c_I.c_bg=c_g.c_I.join(','));c_g.c_G=c_m[c_bf]||(c_m[c_bf]={});c_g.isWired&&c_g.c_h();},value:['playing','active','grayed','over','']},c_z:{name:'text',onChange:c_k.c_y},c_Y:'tooltip'});return c_f;}});


Uize.module({name:'Uize.Widget.PopupPalette',required:['Uize.Node','Uize.Fade','Uize.Widget.Button'],builder:function(c_a){var c_b=true,c_c=false,c_d=Uize.Node;var c_e=c_a.subclass(null,function(){var c_f=this;c_f.fade=new Uize.Fade({duration:750,curve:Uize.Fade.celeration(0,1)});c_f.fade.wire({'Changed.value':function(){c_f.setNodeOpacity('palette',c_f.fade)},Done:function(){c_f.c_g(c_f.c_h)}});var c_i=c_f.c_i=c_f.c_j('selector',function(){c_f.toggle('shown')});c_i.set({clickToDeselect:c_b});c_f.c_k();function c_l(c_m){var c_n=c_m.name=='Over';c_f.c_o&&c_n&&c_f.set({c_h:c_b});c_n?c_f.c_p():c_f.c_q()}c_i.wire({Down:c_r,Over:c_l,Out:c_l});c_s[c_f.instanceId]=c_f;}),c_t=c_e.prototype,c_s={};c_t.c_k=function(){this.c_i.set({selected:this.c_h})};c_t.c_u=function(){return this.c_h&&(this.c_o||this.c_v);};c_t.c_p=function(){this.c_u()&&this.c_w()};c_t.c_q=function(){this.c_u()&&this.c_x()};c_t.c_j=Uize.Widget.Button.addChildButton;c_t.c_g=function(c_y){var c_f=this;c_f.displayNode('palette',c_y);
c_y&&c_f.setNodeStyle('palette',{filter:''});c_f.fire({name:'Palette '+(c_y?'Shown':'Dismissed'),bubble:c_b});};c_t.c_w=function(){var c_f=this;if(c_f.c_z){clearTimeout(c_f.c_z);c_f.c_z=null;}};c_t.c_x=function(){var c_f=this;c_f.c_w();c_f.c_z=setTimeout(function(){c_f.set({c_h:c_c})},250);};c_t.kill=function(){delete c_s[this.instanceId];c_a.prototype.kill.call(this);};c_t.wireUi=function(){var c_f=this;if(!c_f.isWired){c_f.wireNode('palette',{mousedown:c_r,mouseup:function(c_m){c_f.c_A&&c_m.target!=c_f.getNode('palette')&&c_f.set({c_h:c_c});},mouseover:function(){c_f.c_p()},mouseout:function(){c_f.c_q()}});c_f.wireNode('paletteClose','click',function(){c_f.set({c_h:c_c})});if(c_f.c_B!='none'){var c_C=document.body,c_D=c_f.getNode('palette');if(c_D&&c_D.parentNode!=c_C){c_C.insertBefore(c_D,c_C.childNodes[0]);c_f.setNodeStyle(c_D,{zIndex:10000,position:'absolute',left:'',top:'',right:'',bottom:'',width:c_f.getNodeStyle(c_D,'width')});}}c_a.prototype.wireUi.call(c_f);}};c_e.registerProperties({c_E:{
name:'exclusive',value:c_b},c_v:{name:'hideWhenOut',value:c_c},c_A:{name:'hideOnClick',value:c_b},c_B:{name:'positioning',value:'none'},c_h:{name:'shown',onChange:function(){var c_f=this,c_h=c_f.c_h,c_B=c_f.c_B;c_f.c_i&&c_f.c_k();if(c_f.isWired){c_f.c_w();if(c_h){c_f.fire('Before Palette Shown');c_f.c_E&&c_F(c_f);if(c_B!='none'){var c_D=c_f.getNode('palette'),c_G=typeof c_B=='function'?c_B(c_D):c_f.c_i.getNode();function c_H(c_I){c_f.showNode('palette',!c_I);c_f.displayNode('palette',c_I);}if(c_d.isNode(c_G)){c_H(c_b);c_d.setAbsPosAdjacentTo(c_D,c_G);c_H(c_c);}}}if(c_f.fade.get('duration')>0){c_h&&c_f.displayNode('palette');c_f.fade.start({startValue:c_h?0:1,endValue:c_h?1:0});}else{c_f.c_g(c_h);}}},value:c_c},c_o:{name:'showWhenOver',value:c_c}});function c_F(c_J){for(var c_K in c_s){var c_L=c_s[c_K];c_L!=c_J&&c_L.c_E&&c_L.set({c_h:c_c});}}function c_r(){c_M=c_b}if(typeof navigator!='undefined'){var c_M=c_c,c_N=document.onmousedown;document.onmousedown=function(c_m){if(!c_m)c_m=event;c_M?(c_M=c_c):c_F();
typeof c_N=='function'&&c_N(c_m);};}return c_e;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage',superclass:'Uize.Widget.Page',required:['Uize.Node','UizeDotCom.Templates.WidgetToGoTitle','Uize.Widget.PopupPalette'],builder:function(d_a){var d_b=d_a.subclass(null,function(){this.addChild('menu',Uize.Widget.PopupPalette,{hideWhenOut:true,positioning:'absolute'}).fade.set({duration:0});}),d_c=d_b.prototype;d_c.wireUi=function(){var d_d=this;if(!d_d.isWired){Uize.Node.injectHtml(document.body,UizeDotCom.Templates.WidgetToGoTitle.process({idPrefix:d_d.get('idPrefix'),title:document.title}));Uize.module({required:[d_d.d_e,d_d.d_f],builder:function(){d_d.addChild('widget',eval(d_d.d_e),{built:false,html:eval(d_d.d_f)}).insertOrWireUi();}});var d_g=d_d.children.menu,d_h='../'+d_d.d_i.toLowerCase().replace(/\s+/g,'-')+'.html';function d_j(d_k,d_l,d_m,d_n,d_o){page.launchPopup({name:d_k,url:d_l,width:d_m,height:d_n,toolbar:d_o,location:d_o,directories:d_o,status:d_o,menubar:d_o,scrollbars:d_o,resizable:d_o});}function d_p(d_q,d_l){
d_g.wireNode(d_q,'click',function(){d_j(null,d_l,1010,690,1)});}d_p('getThisWidget',d_h);d_p('aboutThisWidget',d_h);d_p('moreWidgets','../../javascript-widgets.html');d_p('uize','../../index.html');d_g.wireNode('openInNewWindow','click',function(){var d_r=Uize.Node.getDimensions(window);d_j('',location.href,d_r.width,d_r.height,0);});d_a.prototype.wireUi.call(d_d);}};d_b.registerProperties({d_i:'title',d_e:'widgetClass',d_f:'widgetHtml'});return d_b;}});


Uize.module({name:'Uize.Node.Event',builder:function(){var _a=function(_b){return _b||event};_a.abort=function(_b){_a.preventDefault(_b||(_b=event));_a.stopPropagation(_b);};_a.charCode=function(_b){_b||(_b=event);if(_b.ctrlKey||_b.altKey||_b.which<1)return 0;return'charCode'in _b?_b.charCode:_a.keyCode(_b);};_a.fix=function(_b){_b||(_b=event);_b.target=_a.target(_b);_b.relatedTarget=_a.relatedTarget(_b);_b.charCode=_a.charCode(_b);_b.keyCode=_a.keyCode(_b);_b.preventDefault||(_b.preventDefault=_c);_b.stopPropagation||(_b.stopPropagation=_d);return _b;};var _e={Backspace:8,Delete:46,Insert:45,Enter:13,Escape:27,Space:32,Tab:9,PageUp:33,PageDown:34,End:35,Home:36,LeftArrow:37,RightArrow:39,UpArrow:38,DownArrow:40};function _f(_g,_h){_a['isKey'+_g]=function(_b){return _a.keyCode(_b)==_h};}for(var _g in _e)_f(_g,_e[_g]);_a.keyCode=function(_b){return'which'in(_b||(_b=event))?_b.which:_b.keyCode;};function _c(){this.preventDefault?this.preventDefault():(this.returnValue=false);}
_a.preventDefault=function(_b){_c.call(_b||event)};_a.relatedTarget=function(_b){return('relatedTarget'in(_b||(_b=event))?_b.relatedTarget:(_b.type=='mouseout'?_b.toElement:_b.fromElement));};function _d(){this.stopPropagation?this.stopPropagation():(this.cancelBubble=true);}_a.stopPropagation=function(_b){_d.call(_b||event)};_a.target=function(_b){return(_b||(_b=event)).target||_b.srcElement;};return _a;}});


Uize.module({name:'Uize.Tooltip',required:['Uize.Node','Uize.Fade'],builder:function(){var _a=function(){},_b=true,_c=false,_d,_e=Uize.Node;var _f=Uize.getGuid(),_g=[],_h,_i=16;function _j(_k){return _e.getById(typeof _k=='function'?_k():_k);}function _l(){_m()}function _n(_o){if(_o!=_h){if(_o){if(_h){_p.stop();_q();}if(!_o._r){_e.wire(document.body,'scroll',_l,_f);_e.wire(document.documentElement,'mousemove',_l,_f);}_h=_o;_e.setStyle(_h._s,{position:'absolute',zIndex:5000,left:-50000,top:-50000});_e.display(_h._s);_m();}else{_p.get('duration')>0?_p.start():_q();}}else if(_o){_p.stop();_e.setOpacity(_h._s,1);}}_a.showTooltip=function(_k,_t,_r){if(_k=_j(_k)){if(_t!==_c){_g.push({_s:_k,_r:_r});}else{for(var _u=_g.length;--_u> -1;)if(_g[_u]._s==_k)break;_u> -1&&_g.splice(_u,1);}_n(_g[_g.length-1]);}};_a.hideTooltip=function(_k){_a.showTooltip(_k,_c)};var _m=_a.positionTooltip=function(_k,_v){_h&&(_k===_d?(_k=_h._s):_h._s==_j(_k))&&_e.setAbsPos(_k,_e.getEventAbsPos(_v),_i);};
var _p=_a.fade=new Uize.Fade({duration:0});function _q(){_h._r||_e.unwireEventsByOwnerId(_f);_e.display(_h._s,_c);_e.setOpacity(_h._s,1);_h=null;}_p.wire({'Changed.value':function(){_e.setOpacity(_h._s,1-_p.get('progress'))},Done:_q});return _a;}});


Uize.module({name:'Uize.Templates'});

Uize.module ({name:'UizeDotCom.WidgetToGoPage.library'});

